import prisma from "../db.server";
import { sha256Hex } from "../lib/crypto.server";
import { createAuditEvent } from "./audit.server";
import { generateEvidencePack } from "./evidence.server";
import type { ShopContext } from "./shop-context.server";
import { getStorageService } from "./storage.server";

const DEMO_ORDER_ID = "gid://shopify/Order/1042";
const DEMO_DISPUTE_ID = "gid://shopify/ShopifyPaymentsDispute/7001";

export async function seedDemoData(context: ShopContext) {
  await prisma.shop.update({
    where: { id: context.shop.id },
    data: {
      settings: {
        storeDisplayName: "Backstop Demo Store",
        defaultPolicyText: "Demo policy: Orders are packed and shipped to the customer-provided shipping address.",
        refundPolicy: "Demo refund policy: Refund requests are reviewed with order, fulfillment, and return records.",
        shippingPolicy: "Demo shipping policy: Fulfilled orders are shipped with carrier tracking when available.",
        responseTone: "factual",
        retentionDays: 180,
        dueSoonDays: 5,
        allowStaffInitials: true,
      },
    },
  });
  const proof = await prisma.proofCapture.create({
    data: {
      shopId: context.shop.id,
      shopifyOrderId: DEMO_ORDER_ID,
      orderName: "#1042",
      status: "DRAFT",
      staffLabel: "JR",
      stationLabel: "Demo station",
      notes: "Demo proof capture generated by Backstop Proof.",
    },
  });
  await createAuditEvent({
    shopId: context.shop.id,
    entityType: "ProofCapture",
    entityId: proof.id,
    action: "proof.created",
    actorType: "SYSTEM",
  });
  const storage = getStorageService();
  for (const stage of ["products-laid-out", "inside-box", "sealed-label"]) {
    const body = Buffer.from(demoSvg(stage));
    const storageResult = await storage.write({
      shopDomain: context.shopDomain,
      key: `demo-proof/${proof.id}/${stage}.svg`,
      body,
      contentType: "image/svg+xml",
    });
    const file = await prisma.proofFile.create({
      data: {
        proofCaptureId: proof.id,
        shopId: context.shop.id,
        storageKey: storageResult.storageKey,
        originalFilename: `${stage}.svg`,
        mimeType: "image/svg+xml",
        byteSize: body.byteLength,
        sha256: await sha256Hex(body),
      },
    });
    await createAuditEvent({
      shopId: context.shop.id,
      entityType: "ProofCapture",
      entityId: proof.id,
      action: "proof.file_uploaded",
      actorType: "SYSTEM",
      metadata: { proofFileId: file.id, sha256: file.sha256 },
    });
  }
  const sealed = await prisma.proofCapture.update({
    where: { id: proof.id },
    data: { status: "SEALED", sealedAt: new Date() },
  });
  await createAuditEvent({
    shopId: context.shop.id,
    entityType: "ProofCapture",
    entityId: proof.id,
    action: "proof.sealed",
    actorType: "SYSTEM",
  });
  const evidence = await generateEvidencePack({
    context: {
      ...context,
      shop: await prisma.shop.findUniqueOrThrow({ where: { id: context.shop.id } }),
    },
    orderId: DEMO_ORDER_ID,
    disputeId: DEMO_DISPUTE_ID,
    proofCaptureId: proof.id,
    reason: "product_not_received",
    communications: "Demo communication: customer confirmed the delivery address before fulfillment.",
  });
  return { proofCapture: sealed, evidencePack: evidence.pack };
}

function demoSvg(label: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360" viewBox="0 0 640 360">
  <rect width="640" height="360" fill="#f4f6f8"/>
  <rect x="44" y="42" width="552" height="276" rx="8" fill="#ffffff" stroke="#9aa4af"/>
  <text x="72" y="120" font-family="Arial" font-size="32" fill="#16202a">Backstop Proof Demo</text>
  <text x="72" y="174" font-family="Arial" font-size="24" fill="#3f4a55">${label}</text>
  <text x="72" y="230" font-family="Arial" font-size="18" fill="#64707d">Hash-sealed demo proof asset</text>
</svg>`;
}
