import { writeFile } from "node:fs/promises";
import { describe, expect, it, vi } from "vitest";
import { PDFDocument, PDFPage } from "pdf-lib";
import deliveredOrder from "../../fixtures/shopify/order.physical-delivered.json";
import { generateEvidencePdf, type EvidencePdfInput } from "../../app/services/pdf.server";

const trackingUrl = `https://tracking.example.invalid/track?reference=${"ABC123".repeat(700)}`;
const fixture: EvidencePdfInput = {
  packId: "pack_layout_fixture", shopName: "北川商店 — Müller & Co.",
  order: {
    ...deliveredOrder,
    customer: { ...deliveredOrder.customer, firstName: "Zoë", lastName: "山田" },
    shippingAddress: { ...deliveredOrder.shippingAddress, name: "Zoë 山田", address1: "東京都渋谷区神宮前 1-2-3" },
    lineItems: { nodes: [{ title: "陶器のマグカップ — Crème brûlée", quantity: 1 }] },
    fulfillments: [{ ...deliveredOrder.fulfillments[0], trackingInfo: [{ company: "日本郵便", number: "JP123456789", url: trackingUrl }] }],
  },
  proofFiles: [], auditEvents: [], completeness: { score: 65, missingItems: ["Customer communication"] },
  rebuttalText: "注文と梱包記録をご確認ください。", policyText: "返品条件 — 未使用品に限ります。",
  communications: "Merci, Zoë. ご確認ありがとうございます。", rawSnapshot: { note: "原文を保持" },
};

describe("PDF multilingual text and layout", () => {
  it("preserves multilingual names/items and paginates a long unbroken URL within page bounds", async () => {
    const drawn = vi.spyOn(PDFPage.prototype, "drawText");
    try {
      const bytes = await generateEvidencePdf(fixture);
      const pdf = await PDFDocument.load(bytes);
      expect(pdf.getPageCount()).toBeGreaterThan(2);
      const texts = drawn.mock.calls.map(([text]) => text);
      expect(texts).toContain("Tracking URL (continued)");
      expect(texts.join("\n")).toContain(fixture.shopName);
      expect(texts.join("\n")).toContain("Zoë 山田");
      expect(texts.join("\n")).toContain("陶器のマグカップ — Crème brûlée");
      const urlStart = texts.findIndex((text) => text.startsWith("https://tracking.example.invalid/"));
      expect(urlStart).toBeGreaterThan(-1);
      let recovered = "";
      for (let index = urlStart; recovered.length < trackingUrl.length; index += 1) {
        const text = texts[index];
        if (text !== "Tracking URL (continued)") recovered += text;
      }
      expect(recovered).toBe(trackingUrl);
      for (const [text, options] of drawn.mock.calls) {
        if (!text || !options?.font || !options.size || options.x === undefined || options.y === undefined) continue;
        expect(options.x + options.font.widthOfTextAtSize(text, options.size), text).toBeLessThanOrEqual(558.01);
        expect(options.y, text).toBeGreaterThanOrEqual(text.startsWith("Generated by Backstop Proof") ? 28 : 54);
        expect(options.y, text).toBeLessThanOrEqual(738);
      }
      const footers = texts.filter((text) => text.startsWith("Generated by Backstop Proof"));
      expect(footers).toHaveLength(pdf.getPageCount());
      if (process.env.BACKSTOP_PDF_INSPECTION_PATH) await writeFile(process.env.BACKSTOP_PDF_INSPECTION_PATH, bytes);
    } finally { drawn.mockRestore(); }
  });

  it("reports an unsupported character explicitly instead of replacing the original", async () => {
    await expect(generateEvidencePdf({ ...fixture, shopName: "Shop 😀" }))
      .rejects.toThrow(/does not support U\+1F600.*not replaced/);
  });

  it("lays out pasted tabs as spaces without dropping the surrounding evidence text", async () => {
    const drawn = vi.spyOn(PDFPage.prototype, "drawText");
    try {
      await generateEvidencePdf({
        ...fixture,
        policyText: "Return\tcondition",
        communications: "Item\tQuantity\nCup\t1",
      });
      const texts = drawn.mock.calls.map(([text]) => text);
      expect(texts).toContain("Return    condition");
      expect(texts).toContain("Item    Quantity");
      expect(texts).toContain("Cup    1");
      expect(texts.some((text) => text.includes("\t"))).toBe(false);
    } finally { drawn.mockRestore(); }
  });
});
